name: SonarCloud
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.head.repo.fork }}
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
          submodules: recursive
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: '^1.24'
      - name: Install dependencies
        run: go install
        working-directory: ${{ env.relativePath }}
      - name: Build SDK project
        run: go build
        working-directory: ${{ env.relativePath }}
      - name: Run unit tests
        run: go test -coverprofile cover.out -coverpkg=./... ./...
        working-directory: ${{ env.relativePath }}
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@ba9859eae8dd6bd29e412f25ddbbef3d032000f4 # v8.2.2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}